application: smughost
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /prefs
  script: prefs.py
  login: admin

- url: /category/.*
  script: category.py

- url: /album/.*
  script: album.py

- url: .*
  script: main.py
