application: smughost
version: 2
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /static
  static_dir: static

- url: /prefs
  script: prefs.py
  login: admin

- url: /category/.*
  script: category.py

- url: /album/.*
  script: album.py

- url: .*
  script: main.py
